name: Python package

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: check out repo content
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: run script
      run: |
        dir
        python run.py
        dir
      env:
        USERNAME: ${{ secrets.REDDIT_USERNAME }}
