name: Python package

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo content
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: run script
      run: |
        output=$(python run.py)
        id = step1
      env:
        USERNAME: ${{ secrets.REDDIT_USERNAME }}
    - name: check again
      run: |
        dir
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: myfile
        path: mydir
